# Generated by Django 4.1.3 on 2022-11-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shorter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(auto_created=True, max_length=7)),
                ('long_link', models.CharField(help_text='Copy here your loooong link', max_length=200)),
                ('short_link', models.CharField(max_length=30)),
                ('days_alive', models.IntegerField(max_length=3)),
                ('is_expired', models.BooleanField(default=False)),
            ],
        ),
    ]
